name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.10.4
homepage: https://github.com/brianegan/chewie

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  video_player:
    git:
      url: https://github.com/kono0514/plugins.git
      path: packages/video_player/video_player
  # video_player:
  #   path: ../plugins/packages/video_player/video_player
  cupertino_icons: ">=1.0.0 <2.0.0"
  wakelock: ">=0.1.2 <1.0.0"
  auto_orientation:
    git: https://github.com/kono0514/auto_orientation

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
